---
driver:
  name: proxy
  port: 5985
  reset_command: "exit 0"

transport:
  name: winrm
  username: 'ChefPowerShell'
  password: 'P2ssw0rd!'

provisioner:
  wait_for_retry: 90
  retry_on_exit_code:
    - 35

verifier:
  name: inspec

platforms:
  - name: windows-server-2016
    driver:
      host: chefconf-<CHANGE_ME>.centralus.cloudapp.azure.com
